# str should generate human readable strings
# Important to remember: str is also the constructor for strings
# The default implementation of __str__ is to call __repr__ of the object. So, if __str__ is not implemented but
# __repr is, the returned string will be generated by __repr__


class Point2D:

    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __str__(self):
        return '{point.x}, {point.y}'.format(point=self)

    def __repr__(self):
        return 'Point2D(x={}, y={})'.format(self.x, self.y)


if __name__ == '__main__':
    point = Point2D(x=10, y=20)
    print('The circle is centered at ({})'.format(str(point)))

    # In the above case, print the class name would be too much and too implementation specific to the clients
    # If the idea is to be human readable, the class name does not make sense
